# Generated by Django 3.1.7 on 2021-05-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
    ]
