# Generated by Django 3.1.7 on 2021-05-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210513_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body1',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body5',
        ),
    ]
