# Generated by Django 3.1.7 on 2021-05-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210514_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_credits',
            field=models.TextField(blank=True, default=''),
        ),
    ]
